backend:
  name: git-gateway
  branch: main

media_folder: "최신 웹페이지/images/uploads"
public_folder: "/images/uploads"

locale: "ko"

collections:
  - name: "posts"
    label: "글"
    label_singular: "글"
    folder: "최신 웹페이지/content/posts"
    create: true
    delete: true
    slug: "{{fields.slug}}"
    extension: "md"
    format: "frontmatter"
    summary: "{{title}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "URL주소(영문 소문자, 띄어쓰기 대신 -)", name: "slug", widget: "string" }
      - { label: "카테고리", name: "category", widget: "string", default: "금융/신용" }
      - { label: "태그", name: "tags", widget: "list", default: [] }
      - { label: "요약", name: "summary", widget: "text" }
      - { label: "날짜", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
      - { label: "본문", name: "body", widget: "markdown" }
